# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
      - stage
    exclude:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  CONTAINER_REGISTRY: apimanalytics.azurecr.io
  ANALYTICS_REPOSITORY: choreo-apim/analytics-api
  TAG: v0.1.0

steps:
  - template: templates/install-kustomize.yml
  - script: |
      set -eo pipefail
      cd kustomize
      mkdir build
      cd stage
      $KUSTOMIZE edit set image ${{ CONTAINER_REGISTRY }}/${{ ANALYTICS_REPOSITORY }}=${{ CONTAINER_REGISTRY }}/${{ ANALYTICS_REPOSITORY }}:${{ TAG }}
      echo ${{ CONTAINER_REGISTRY }}/${{ ANALYTICS_REPOSITORY }}=${{ CONTAINER_REGISTRY }}/${{ ANALYTICS_REPOSITORY }}:${{ TAG }}
    displayName: 'Generate k8s artifacts'

