# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
      - stage
    exclude:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - template: templates/install-kustomize.yml
  - script: |
      set -eo pipefail
      cd kustomize
      mkdir build
      cd stage
      $KUSTOMIZE edit set image apimanalytics.azurecr.io/choreo-apim/analytics-api=apimanalytics.azurecr.io/choreo-apim/analytics-api:v4
      cd ..
      $KUSTOMIZE build stage | tee build/kustomize-all.yml
    displayName: 'Generate k8s artifacts'
  - template: templates/install-kapp.yml
  - task: AzureCLI@1
    displayName: 'Generate kube config'
    inputs:
      azureSubscription: 'azure-cli'
      scriptLocation: inlineScript
      inlineScript: 'az aks get-credentials --resource-group APIM-RnD-RG --name apim-poc --admin'
  - script: |
      $KAPP version
      $KAPP -y deploy -a stage-analytics-api --apply-default-update-strategy=fallback-on-replace --diff-changes -f kustomize/build/kustomize-all.yml -f kustomize/base/kapp-config.yaml
    displayName: "Deploy to cluster"

