# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: 'ubuntu-latest'

resources:
  webhooks:
    - webhook: analyticsapidev
      connection: analytic-api-dev-build


steps:
  - script: echo Hello, world! ${{parameters.analyticsapidev.newDockerImage}}
    displayName: 'Run a one-line script'
  - template: templates/install-kustomize.yml
  - script: |
      set -eo pipefail
      cd kustomize
      mkdir build
      $KUSTOMIZE build dev | tee build/kustomize-all.yml
    displayName: 'Generate k8s artifacts'
  - template: templates/install-kapp.yml
  - task: AzureCLI@1
    displayName: 'Generate kube config'
    inputs:
      azureSubscription: 'choreo-non-prod-rg'
      scriptLocation: inlineScript
      inlineScript: 'az aks get-credentials --resource-group APIM-RnD-RG --name apim-poc --admin'
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
