apiVersion: kapp.k14s.io/v1alpha1
kind: Config

rebaseRules:
  - path: [spec, replicas]
    type: copy
    sources: [existing, new]
    resourceMatchers:
      - apiVersionKindMatcher:
          apiVersion: apps/v1
          kind: Deployment

  - path: [metadata, annotations, autoscaling.alpha.kubernetes.io/current-metrics]
    type: copy
    sources: [existing, new]
    resourceMatchers:
      - apiVersionKindMatcher:
          apiVersion: autoscaling/v1
          kind: HorizontalPodAutoscaler

  - path: [metadata, annotations, autoscaling.alpha.kubernetes.io/conditions]
    type: copy
    sources: [existing, new]
    resourceMatchers:
      - apiVersionKindMatcher:
          apiVersion: autoscaling/v1
          kind: HorizontalPodAutoscaler

  - paths:
      - [metadata, annotations, pv.kubernetes.io/bound-by-controller]
      - [spec, claimRef]
    type: copy
    sources: [existing, new]
    resourceMatchers:
      - apiVersionKindMatcher:
          apiVersion: v1
          kind: PersistentVolume
